version: '3'
services:
  
  mysql:
    container_name: mysqlcontainer
    image: mysql/mysql-server:8.0.24-1.2.2-server
    environment:  
        MYSQL_ROOT_PASSWORD: senhaforte
        MYSQL_ROOT_HOST: "%"
    volumes:
        - ./dbdata:/var/lib/mysql
        - ./database:/docker-entrypoint-initdb.d
    networks:
        - ntw-app-db
    restart: always
  
  node:
    container_name: nodecontainer
    build:
        context: node 
    depends_on:
        - mysql    
    networks:
        - ntw-app-db
    entrypoint:  dockerize -wait tcp://mysql:3306 -timeout 30s sh -c "node index.js"
    volumes:
      - "./node:/usr/src/app"
      - /usr/src/app/node_modules
    # command: "node index.js"
  
  nginx:
    container_name: nginxcontainer
    build:
        context: nginx 
    ports: 
        - 8080:80
    restart: on-failure
    depends_on:
        - node    
    networks:
        - ntw-app-db

networks:
    ntw-app-db:
        driver: bridge      
 
